### ISSUE TITLE
If-then flow created

### ISSUE THREAD

**Issue by henkvancann** [henkvancann/MOOC-trials#12]
https://github.com/henkvancann/MOOC-trials/blob/master/quizSeedTool.md#its-been-a-while-since-you-last-used-gordian-seed-tool-app-will-the-updated--new-version-of-seed-tool-still-work-for-old-shares

Here are two new questions to put in Moodle. However, this would be questionnaire 2.

The flow is : questionnaire 1 if passed -> 2, if not passed -> go back to  1 (and repeat the l[ist of course material links](https://github.com/henkvancann/MOOC-trials/blob/master/course-material-links.md)).

<img src="https://user-images.githubusercontent.com/479356/159457805-51f16164-d2a0-4d66-aead-b2bb67483663.jpeg" alt="Flow" border="0" width="200">

**Comment by romanova1** [comment]
I created the first quiz as a course (one quiz one course). I can't add any other resources or activities.

We can have a course page with multiple quizzes and different resources.

In both cases I can implement the if-then flow. The less complicated way is to have a course page with multiple resources, because the users won't have to access different courses for each quiz.

Let me know which option is the best.

**Comment by henkvancann** [comment]
The least complicated way

**Comment by romanova1** [comment]
![Screenshot 2022-03-24 111340](https://user-images.githubusercontent.com/36804362/159894153-0564eed0-4129-4111-938b-424a17e34540.png)
